name: 'Comment on Issue'
branding:
  icon: 'message-circle'  
  color: 'blue'
description: 'Comments on an issue with the provided message'
inputs: 
  message:
    description: 'Comment message'
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.GITHUB_TOKEN }}
