name: pr-checklist

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2alpha1
      with:
        message: "Did you go through all of the troubleshooting steps outlined in README.md?\nDid you describe what you've tried in the PR description?"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
